"""Initial migration

Revision ID: 0bf3dac4df5a
Revises: 
Create Date: 2025-09-07 19:29:42.025975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf3dac4df5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('horas_presenciales', sa.Integer(), nullable=False),
    sa.Column('horas_mixtas', sa.Integer(), nullable=False),
    sa.Column('horas_autonomas', sa.Integer(), nullable=False),
    sa.Column('cantidad_creditos', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bloque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('pass_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restriccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('restriccion_blanda', sa.Text(), nullable=True),
    sa.Column('restriccion_dura', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('asignatura_id', sa.Integer(), nullable=True),
    sa.Column('cupos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.Column('bloque_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bloque_id'], ['bloque.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['sala.id'], ),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clase')
    op.drop_table('seccion')
    op.drop_table('restriccion')
    op.drop_table('sala')
    op.drop_table('docente')
    op.drop_table('bloque')
    op.drop_table('asignatura')
    # ### end Alembic commands ###
