"""modificacion_tablas_bd

Revision ID: b2ae188175d1
Revises: f1a2b3c4d5e6
Create Date: 2025-09-30 23:16:34.146336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ae188175d1'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrador',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('permisos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edificio',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('pisos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiante',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('matricula', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('asignatura', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('asignatura', 'codigo',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('asignatura', 'nombre',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('bloque', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('clase', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('clase', 'seccion_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('clase', 'docente_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('clase', 'sala_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('clase', 'bloque_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('docente', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('docente', sa.Column('departamento', sa.Text(), nullable=True))
    op.alter_column('docente', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('docente_id_seq'::regclass)"))
    op.create_foreign_key(None, 'docente', 'user', ['user_id'], ['id'])
    op.drop_column('docente', 'pass_hash')
    op.drop_column('docente', 'nombre')
    op.drop_column('docente', 'email')
    op.add_column('restriccion', sa.Column('activa', sa.Boolean(), nullable=True))
    op.alter_column('restriccion', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('restriccion', 'docente_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # Convert text data to boolean values before changing column type
    op.execute("""
        UPDATE restriccion 
        SET restriccion_blanda = CASE 
            WHEN restriccion_blanda IS NULL OR restriccion_blanda = '' THEN NULL
            ELSE 'true'
        END
    """)
    op.execute("""
        UPDATE restriccion 
        SET restriccion_dura = CASE 
            WHEN restriccion_dura IS NULL OR restriccion_dura = '' THEN NULL
            ELSE 'true'
        END
    """)
    # Now convert the columns to boolean type
    op.execute("ALTER TABLE restriccion ALTER COLUMN restriccion_blanda TYPE BOOLEAN USING restriccion_blanda::boolean")
    op.execute("ALTER TABLE restriccion ALTER COLUMN restriccion_dura TYPE BOOLEAN USING restriccion_dura::boolean")
    op.add_column('restriccion_horario', sa.Column('activa', sa.Boolean(), nullable=True))
    op.alter_column('restriccion_horario', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('restriccion_horario', 'docente_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('sala', sa.Column('edificio_id', sa.BigInteger(), nullable=True))
    op.add_column('sala', sa.Column('disponible', sa.Boolean(), nullable=True))
    op.add_column('sala', sa.Column('equipamiento', sa.Text(), nullable=True))
    op.alter_column('sala', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('sala_id_seq'::regclass)"))
    op.alter_column('sala', 'codigo',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'sala', 'edificio', ['edificio_id'], ['id'])
    op.alter_column('seccion', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('seccion', 'codigo',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('seccion', 'asignatura_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # Add new columns as nullable first
    op.add_column('user', sa.Column('nombre', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('pass_hash', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('rol', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('activo', sa.Boolean(), nullable=True))
    
    # Update existing users with data from existing columns
    op.execute("""
        UPDATE "user" 
        SET nombre = COALESCE(first_name || ' ' || last_name, 'Usuario'),
            pass_hash = COALESCE(password_hash, ''),
            rol = 'usuario',
            activo = COALESCE(is_active, true)
    """)
    
    # Now make columns NOT NULL where required
    op.alter_column('user', 'nombre', nullable=False)
    op.alter_column('user', 'pass_hash', nullable=False)
    op.alter_column('user', 'rol', nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.alter_column('user', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user', 'activo')
    op.drop_column('user', 'rol')
    op.drop_column('user', 'pass_hash')
    op.drop_column('user', 'nombre')
    op.alter_column('seccion', 'asignatura_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('seccion', 'codigo',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('seccion', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'sala', type_='foreignkey')
    op.alter_column('sala', 'codigo',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sala', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('sala_id_seq'::regclass)"))
    op.drop_column('sala', 'equipamiento')
    op.drop_column('sala', 'disponible')
    op.drop_column('sala', 'edificio_id')
    op.alter_column('restriccion_horario', 'docente_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('restriccion_horario', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('restriccion_horario', 'activa')
    op.execute("ALTER TABLE restriccion ALTER COLUMN restriccion_dura TYPE TEXT USING restriccion_dura::text")
    op.execute("ALTER TABLE restriccion ALTER COLUMN restriccion_blanda TYPE TEXT USING restriccion_blanda::text")
    op.alter_column('restriccion', 'docente_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('restriccion', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('restriccion', 'activa')
    op.add_column('docente', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('docente', sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('docente', sa.Column('pass_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'docente', type_='foreignkey')
    op.alter_column('docente', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('docente_id_seq'::regclass)"))
    op.drop_column('docente', 'departamento')
    op.drop_column('docente', 'user_id')
    op.alter_column('clase', 'bloque_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('clase', 'sala_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('clase', 'docente_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('clase', 'seccion_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('clase', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('bloque', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('asignatura', 'nombre',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('asignatura', 'codigo',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('asignatura', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('estudiante')
    op.drop_table('edificio')
    op.drop_table('administrador')
    op.drop_table('campus')
    # ### end Alembic commands ###
